---
data_items: []

tags:
- fuel
- defra
- stationary
- combustion
- direct
- indirect
- lca
- calculation
- emission_factor
- UK
- defra_annex1
provenance: "[[http://www.defra.gov.uk/environment/economy/business-efficiency/reporting|DEFRA]]"
gallery:
show: "1"
authority: enterprise
ivds:
  fuel: Type of fuel
  massCO2PerVolume: Quantity of direct CO<sub>2</sub> emitted per unit of fuel consumed
  massCH4PerVolume: Quantity of direct CH<sub>4</sub> emitted per unit of fuel consumed (as CO<sub>2</sub>e)
  massN2OPerVolume: Quantity of direct N<sub>2</sub>O emitted per unit of fuel consumed (as CO<sub>2</sub>e)
  massDirectCO2ePerVolume: Total quantity of direct emissions emitted per unit of fuel consumed (as CO<sub>2</sub>e)
  massIndirectCO2ePerVolume: Quantity of indirect emissions per unit of fuel consumed (as CO<sub>2</sub>e)
  massTotalCO2ePerVolume: Total quantity of ALL emissions emitted per unit of fuel consumed (as CO<sub>2</sub>e)
  volume: Quantity of fuel consumed
wikiname: Volume_based_fuel_combustion_by_DEFRA
