---
data_items: []

tags:
- fuel
- defra
- stationary
- combustion
- direct
- indirect
- lca
- calculation
- emission_factor
- UK
- defra_annex1
provenance: "[[http://www.defra.gov.uk/environment/economy/business-efficiency/reporting|DEFRA]]"
gallery:
show: "1"
authority: enterprise
ivds:
  fuel: Type of fuel
  basis: Calorific basis
  massCO2PerEnergy: Quantity of direct CO<sub>2</sub> emitted per unit of energy consumed
  massCH4PerEnergy: Quantity of direct CH<sub>4</sub> emitted per energy unit of consumed (as CO<sub>2</sub>e)
  massN2OPerEnergy: Quantity of direct N<sub>2</sub>O emitted per energy unit of consumed (as CO<sub>2</sub>e)
  massDirectCO2ePerEnergy: Total quantity of direct emissions emitted per energy unit of consumed (as CO<sub>2</sub>e)
  massIndirectCO2ePerEnergy: Quantity of indirect emissions per energy unit of consumed (as CO<sub>2</sub>e)
  massTotalCO2ePerEnergy: Total quantity of ALL emissions emitted per energy unit of consumed (as CO<sub>2</sub>e)
  energy: Quantity of energy consumed
wikiname: Energy_based_fuel_combustion_by_DEFRA
