---
data_items: []

tags:
- transport
- defra
- heavy_goods
- distance
- defra_annex7
- calculation
- emission_factor
- direct
- indirect
- lca
- UK
provenance: "[[http://www.defra.gov.uk/environment/economy/business-efficiency/reporting|DEFRA]]"
gallery:
show: "1"
authority: enterprise
ivds:
  type: Type of vehicle
  size: Size of vehicle (gross vehicle weight)
  load: Proportion of vehicle which is laden with goods (%)
  massCO2PerDistance: Quantity of direct CO<sub>2</sub> emissions per unit distance
  massCH4PerDistance: Quantity of direct CH<sub>4</sub> emissions per unit distance (CO<sub>2</sub>e)
  massN2OPerDistance: Quantity of direct N<sub>2</sub>O emissions per unit distance (CO<sub>2</sub>e)
  massDirectCO2ePerDistance: Quantity of direct greenhouse gas emissions per unit distance (CO<sub>2</sub>e)
  massIndirectCO2ePerDistance: Quantity of indirect greenhouse gas emissions per unit distance (CO<sub>2</sub>e)
  massTotalCO2ePerDistance: Total quantity of greenhouse gas emissions per unit distance (CO<sub>2</sub>e)
  distance: Distance travelled
wikiname: DEFRA_heavy_goods_vehicle_methodology
