---
data_items: []

tags:
- transport
- defra
- passenger
- public
- distance
- plane
- taxi
- bus
- train
- ship
- defra_annex6
- calculation
- emission_factor
- direct
- indirect
- lca
- UK
provenance: "[[http://www.defra.gov.uk/environment/economy/business-efficiency/reporting|DEFRA]]"
gallery:
show: "1"
authority: enterprise
ivds:
  type: Type of transport
  subtype: Subtype of transport
  passengerClass: Passenger class/mode
  massCO2PerDistancePerPassenger: Quantity of direct CO<sub>2</sub> emissions per unit distance
  massCH4PerDistancePerPassenger: Quantity of direct CH<sub>4</sub> emissions per unit distance (CO<sub>2</sub>e)
  massN2OPerDistancePerPassenger: Quantity of direct N<sub>2</sub>O emissions per unit distance (CO<sub>2</sub>e)
  massDirectCO2ePerDistancePerPassenger: Quantity of direct greenhouse gas emissions per unit distance (CO<sub>2</sub>e)
  massIndirectCO2ePerDistancePerPassenger: Quantity of indirect greenhouse gas emissions per unit distance (CO<sub>2</sub>e)
  massTotalCO2ePerDistancePerPassenger: Total quantity of greenhouse gas emissions per unit distance (CO<sub>2</sub>e)
  distance: Distance travelled
  passengers: Number of passengers
wikiname: DEFRA_passenger_transport_methodology
usages:
  default: { passengers : optional }
