---
data_items: []

tags:
- transport
- GHGP
- global
- calculation
- emission_factor
- direct
- GHGP_cross_sector
- GHGP_adipic_acid_sector
- GHGP_aluminum_sector
- GHGP_ammonia_sector
- GHGP_cement_sector
- GHGP_hcfc22_sector
- GHGP_iron_and_steel_sector
- GHGP_lime_sector
- GHGP_nitric_sector
- GHGP_pulp_and_paper_sector
- GHGP_refrigeration_sector
- GHGP_semiconductor_sector
- GHGP_wood_sector
provenance: "[[http://www.ghgprotocol.org/calculation-tools/all-tools|Greenhouse Gas Protocol]]"
gallery: |-
  <%= chart :dependent => 'massCO2PerMassDistance' %>
show: "1"
authority: enterprise
ivds:
  type: Type of freight transport
  subtype: Subtype of freight transport
  size: Size of freighting vehicle
  region: Geographic region
  massCO2PerMassDistance: Quantity of CO<sub>2</sub> per units distance and mass freighted
  massCH4PerMassDistance: Quantity of CH<sub>4</sub> per units distance and mass freighted
  massN2OPerMassDistance: Quantity of N<sub>2</sub>O per units distance and mass freighted
  distance: Distance freighted
  mass: Quantity freighted
wikiname: Freight_transport_by_Greenhouse_Gas_Protocol
name: "Freight transport by Greenhouse Gas Protocol"
