---
data_items: []

tags:
- fuel
- stationary
- combustion
- EPA
- US
- CH4
- N2O
- climate_leaders
- data
- direct
- emission_factor
- EPA_mandatory
- EPA_mandatory_fuel
provenance: "[[http://www.epa.gov/stateply/resources/index.html|US EPA/Climate Leaders]]"
gallery:
show: "1"
authority: enterprise
ivds:
  massCH4PerEnergy: CH<sub>4</sub> emissions per quantity of energy consumed
  massN2OPerEnergy: N<sub>2</sub>O emissions per quantity of energy consumed
  type: Type of fuel
  context: Context in which fuel burned
  source:
wikiname: CH4_and_N20_emissions_from_stationary_combustion
