---
data_items: []

tags:
- agriculture
- IPCC
- IPCC_agriculture
- IPCC_agriculture_livestock
- IPCC_tier1
- livestock
- manure
- N2O
- poultry
- calculation
- direct
- emission_factor
- physical_properties
- global
provenance: "[[http://www.ipcc-nggip.iges.or.jp/public/2006gl/pdf/4_Volume4/V4_10_Ch10_Livestock.pdf|IPCC]]"
gallery: "nil"
show: "1"
authority: enterprise
ivds:
  region: Geographic region
  poultrySubtype: Type of poultry
  fractionVolatilised: The fraction of manure-N which is typically volatilised
  massNExcretedPer1000kgLivestockPerTime: The typical daily quantity of manure-N produced per tonne of livestock
  managementType: Type of manure management employed
  source:
  massN2OPerMassNDirect: The rate at which manure-N is directly converted to N<sub>2</sub>O-N
  totalLiveweight: Total mass of livestock under consideration
  massN2OPerMassNVolatilised: The rate at which volatilised manure-N is converted to N<sub>2</sub>O-N
wikiname: Poultry_manure_nitrous_oxide_emissions
name: "IPCC methodology for manure sourced nitrous oxide - poultry"
