---
data_items: []

tags:
- deprecated
- home
- business
- water
- electrical
- calculation
- emission_factor
- indirect
- lca
- UK
provenance: "[[http://www.water.org.uk/home/news/press-releases/sustainability-indicators-2008-09/sustainability-2009.pdf|Water UK]]"
gallery:
show: "1"
authority: enterprise
ivds:
  kWhPerLitre: Per volume electricity consumption factor
  kgCO2PerLitre: Per volume CO<sub>2</sub> emissions factor
  litresPerMonth: Water consumption per month
  type: Type of water usage
  volumePerTime: Water consumption
wikiname: Water
