---
data_items: []

tags:
- PFC
- GHGP
- GHGP_aluminum_sector
- aluminium
- IPCC
- IPCC_tier2
- IPCC_tier3
- IPCC_industry
- IPCC_industry_metal
- EPA
- EPA_mandatory
- EPA_mandatory_aluminum
- climate_leaders
- calculation
- direct
- emission_factor
- physical_properties
- global
provenance: "[[http://www.ipcc-nggip.iges.or.jp/public/2006gl/index.html|IPCC]] - [[http://www.ghgprotocol.org/calculation-tools/all-tools|Greenhouse Gas Protocol]]"
gallery:
show: "1"
authority: enterprise
ivds:
  weightFrac: The quantity of C<sub>2</sub>F<sub>6</sub> emitted relative to CF<sub>4</sub> emissions
  cf4Coef: Slope coefficient for CF<sub>4</sub>. This describes the relationship between the anode effect and the rate of CF<sub>4</sub> emissions
  defWeightFrac: Default C<sub>2</sub>F<sub>6</sub>/CF<sub>4</sub> weight fraction. This is used if no facility-specific value is available
  aef: Anode effect frequency. Optional. Ignored if none entered
  alQuantity: Quantity of aluminium produced
  defCf4Coef: Default slope coefficient for CF<sub>4</sub>. This describes the relationship between the anode effect and the rate of CF<sub>4</sub> emissions
  cellType: Type of cell technology employed
  source:
  aem: Anode effect minutes per cell day (i.e. the number of cells operating multiplied by the number of days in operation)
wikiname: Aluminium_PFC_Slope
name: "IPCC methodology for aluminium production PFC emissions - slope approach"
usages:
  default: { weightFrac : optional, cf4Coef : optional, aef : optional }
