---
data_items: []

tags:
- home
- business
- energy
- electricity
- fuel
- US
- price
- calculation
- emission_factor
- direct
provenance: http://www.eia.doe.gov
gallery:
show: "1"
authority: enterprise
ivds:
  currencyUSDPerMonth: Amount ($) spent on energy per month
  currencyUSD: Amount ($) spent on energy
  type: Type of energy used
  source:
  kgCO2PerUSD: Per dollar CO<sub>2</sub> emissions factor
wikiname: US_energy_by_price
