---
data_items: []

tags:
- ice
- construction
- materials
- window
- calculation
- emission_factor
- energy
- lca
provenance: "[[http://people.bath.ac.uk/cj219/|Inventory of Carbon & Energy]]"
gallery:
show: "1"
authority: enterprise
ivds:
  type: Type of window air space fill
  energyPerWindow: Embodied energy per 1.2 m x 1.2 m window unit
  massCO2PerWindow: Embodied CO<sub>2</sub> per 1.2 m x 1.2 m window unit
  boundary: Life cycle analysis boundary, i.e. the stages in the window life cycle which are represented by the energy and CO<sub>2</sub> factors
  note: Author notes on the sourcing of data
  number: Number of windows
wikiname: ICE_v2_window_fills
name: "Inventory of Carbon & Energy methodology for window air space fills"
