---
data_items: []

provenance: Act on CO2
tags:
- UK
- typical
- aggregate
- transport
- data
- benchmark
- direct
- actonco2
authority: recommended
show: "1"
gallery:
ivds:
  ruralOrUrban: Home context
  totalCO2: Typical total CO<sub>2</sub> emissions
  flightsCO2: Typical flight-associated CO<sub>2</sub> emissions
  numberOfPeople: Number of people in household
  carsAndMotorbikesCO2: Typical car/motorcycle-associated CO<sub>2</sub> emissions
  profileType: Individual or household calculation
  source:
wikiname: People_Like_Me_Travel
