---
data_items: []

tags:
- deprecated
- transport
- mobile
- plane
- heavy_goods
- GHGP
provenance: "[[http://www.defra.gov.uk/environment/economy/business-efficiency/reporting|DEFRA]]"
gallery:
show: "0"
authority: enterprise
ivds:
  mass: Mass of freight transported
  type: Type (distance) of flight
  CO2: CO<sub>2</sub> emissions factor
  source:
  distance: Distance freight transported
wikiname: Plane_freighting
