---
data_items: []

tags:
- GHGP
- GHGP_ammonia_sector
- ammonia
- IPCC
- IPCC_tier1
- IPCC_tier2
- IPCC_tier3
- IPCC_industry
- IPCC_industry_chemical
- EPA
- EPA_mandatory
- EPA_mandatory_ammonia
- calculation
- direct
- emission_factor
- physical_properties
- mass_balance
- global
provenance: "[[http://www.ipcc-nggip.iges.or.jp/public/2006gl/index.html|IPCC]] - [[http://www.ghgprotocol.org/calculation-tools/all-tools|Greenhouse Gas Protocol]]"
gallery:
show: "1"
authority: enterprise
ivds:
  plant: Type of plant(s) under consideration
  css: Quantity of CO<sub>2</sub> recovered for carbon capture and storage
  carbonContent: Quantity of carbon per unit of energy yielded
  fuel: Type of feedstock fuel used
  prodProcess: Type of production process employed
  ureaProd: Quantity of CO<sub>2</sub> recovered for urea production
  defFuelQuantity: Default quantity of fuel required per quantity of ammonia produced. Used if no facility-specific data is available
  nh3Quantity: Quantity of ammonia produced
  source:
  oxidationFact: Fraction of fuel fully oxidised. Assumed to be 1 (i.e. 100%) if no facility-specific data is available
  defCarbonContent: Default quantity of carbon per unit of energy yielded. Used if no facility-specific data is available
  fuelQuantity: Quantity of fuel required per quantity of ammonia produced
  totalFuelQuantity: Total quantity of fuel consumed
  quantityUrea: Quantity of urea produced
wikiname: Ammonia
name: "IPCC methodology for ammonia production"
usages:
  ammoniaProductionAndCO2Recovery: { totalFuelQuantity : forbidden, fuelQuantity : optional, carbonContent : optional, oxidationFact : optional, css : optional, ureaProd : optional, quantityUrea : forbidden }
  ammoniaAndUreaProduction: { totalFuelQuantity : forbidden, fuelQuantity : optional, carbonContent : optional, oxidationFact : optional, css : optional, ureaProd : forbidden, quantityUrea : optional }
  fuelConsumptionAndCO2Recovery: { nh3Quantity : forbidden, fuelQuantity : forbidden, carbonContent : optional, oxidationFact : optional, css : optional, ureaProd : optional, quantityUrea : forbidden }
  fuelConsumptionAndUreaProduction: { nh3Quantity : forbidden, fuelQuantity : forbidden, carbonContent : optional, oxidationFact : optional, css : optional, ureaProd : forbidden, quantityUrea : optional }
  order: [ ammoniaProductionAndCO2Recovery, ammoniaAndUreaProduction, fuelConsumptionAndCO2Recovery, fuelConsumptionAndUreaProduction ]
