---
data_items: []

tags:
- EPA
- pca
- US
- egrid
- electricity
- grid
- calculation
- emission_factor
- direct
provenance: "[[http://www.epa.gov/cleanenergy/energy-resources/egrid/index.html|EPA-eGRID]]"
gallery:
show: "1"
authority: enterprise
ivds:
  area: Name of Power Control Area
  type: Type of power
  massNOxPerEnergy: Mass of nitrogen oxides emitted per unit quantity of electricity
  massOzoneSeasonNOxPerEnergy: Mass of nitrogen oxides emitted per unit quantity of electricity during the ozone season (May-September)
  massSO2PerEnergy: Mass of sulphur dioxide emitted per unit quantity of electricity
  massCO2PerEnergy: Mass of carbon dioxide emitted per unit quantity of electricity
  massCH4PerEnergy: Mass of methane emitted per unit quantity of electricity
  massN2OPerEnergy: Mass of nitrous oxide emitted per unit quantity of electricity
  massCO2ePerEnergy: Mass of CO<sub>2</sub>e emitted per unit quantity of electricity
  massHgPerEnergy: Mass of mercury oxides emitted per unit quantity of electricity
  gridRegion: Parent grid of region
  energy: Quantity of electricity under consideration
  includeTransmissionLosses: Set to true to include transmission losses, resulting in a calculation representing emissions associated with electricity consumed. Set to false to calculate emissions associated with electricity supplied to the grid
name: "eGRID methodology for US electricity by Power Control Area"
wikiname: "EPA_eGRID_by_Power_Control_Area"
usages:
  default: {includeTransmissionLosses: optional}
