---
data_items: []

tags:
- electricity
- generation
- distribution
- transmission
- losses
- defra
- UK
- calculation
- direct
- indirect
- lca
- emission_factor
- defra_annex3
provenance: "[[http://www.defra.gov.uk/environment/economy/business-efficiency/reporting|DEFRA]]"
gallery:
show: "1"
authority: enterprise
ivds:
  type: Type of activity (e.g. generation, consumption)
  emission: Type of emission (e.g. direct, indirect)
  basis: basis for emissions data/calculation (e.g. annual, rolling average)
  massCO2PerEnergy: Quantity of CO<sub>2</sub> emitted per unit of electricity
  massCH4PerEnergy: Quantity of CH<sub>4</sub> (as CO<sub>2</sub>e) emitted per unit of electricity
  massN2OPerEnergy: Quantity of N<sub>2</sub>O (as CO<sub>2</sub>e) emitted per unit of electricity
  massCO2ePerEnergy: Quantity of total CO<sub>2</sub>e emitted per unit of electricity
  energyConsumed: Quantity of energy consumed
wikiname: UK_electricity_by_DEFRA
