---
data_items: []

tags:
- deprecated
- transport
- mobile
- distance
- passenger
- plane
- actonco2
- calculation
- emission_factor
- direct
provenance: "[[http://www.defra.gov.uk/environment/business/reporting/conversion-factors.htm|DEFRA]]"
gallery:
show: "1"
authority: enterprise
ivds:
  IATACode1: Departure airport IATA code
  long2: Destination location longitude
  lat1: Departure location latitude
  kgCO2PerPassengerKm: Per distance CO<sub>2</sub> emissions factor
  journeysPerYear: Number of journeys per year
  journeys: Number of journeys undertaken
  passengerClass: Journey Passenger class category
  lat2: Destination location latitude
  size: Journey size (one-way, return, -)
  IATACode2: Destination airport IATA code
  useRFI:
  numberOfPassengers: Number of passengers under consideration
  kgCO2PerPassengerJourney: Per journey CO<sub>2</sub> emissions factor
  distanceKmPerYear: Total distance travelled per year
  type: Journey type
  radiativeForcingIndex:
  calculatedDistance:
  source:
  distance: Total distance travelled
  long1: Departure location longitude
wikiname: Generic_plane_transport
