---
data_items: []

tags:
- transport
- defra
- distance
- mass
- plane
- road
- train
- ship
- light_goods
- heavy_goods
- defra_annex7
- calculation
- emission_factor
- direct
- indirect
- lca
- UK
provenance: "[[http://www.defra.gov.uk/environment/economy/business-efficiency/reporting|DEFRA]]"
gallery:
show: "1"
authority: enterprise
ivds:
  type: Type of transport
  subtype: Subtype of transport
  size: Size of freight vehicle
  massCO2PerMassPerDistance: Quantity of direct CO<sub>2</sub> emissions per unit mass and unit distance
  massCH4PerMassPerDistance: Quantity of direct CH<sub>4</sub> emissions per unit mass and unit distance (CO<sub>2</sub>e)
  massN2OPerMassPerDistance: Quantity of direct N<sub>2</sub>O emissions per unit mass and unit distance (CO<sub>2</sub>e)
  massDirectCO2ePerMassPerDistance: Quantity of direct greenhouse gas emissions per unit mass and unit distance (CO<sub>2</sub>e)
  massIndirectCO2ePerMassPerDistance: Quantity of indirect greenhouse gas emissions per unit mass and unit distance (CO<sub>2</sub>e)
  massTotalCO2ePerMassPerDistance: Total quantity of greenhouse gas emissions per unit mass and unit distance (CO<sub>2</sub>e)
  distance: Distance freighted
  mass: Mass of goods freighted
  averageLoading: Proportion of vehicle which is typically laden (%)
  averageMassGoods: Absolute quantity of goods typically freighted
wikiname: DEFRA_freight_transport_methodology
